// Every UI string, Bangla first. Bangla = CLAUDE DRAFT: Zoha reviews every line (keep it everyday village Bangla).
// Card texts live in public/data/cards.json; follow-up questions in public/data/knowledge.json.

export const APP_NAME = { bn: "ধানসাথী", en: "DhanSathi" };

export const S = {
  tagline: { bn: "ধানের পাতা আর বন্যার পরামর্শ — ইন্টারনেট ছাড়াই", en: "Rice leaf and flood advice — no internet needed" },
  // Home
  home_check: { bn: "পাতা পরীক্ষা করুন", en: "Check a leaf" },
  home_check_sub: { bn: "ধানপাতার ছবি তুলুন", en: "Take a photo of a rice leaf" },
  home_flood: { bn: "বন্যা বা খরার পরে", en: "After flood or drought" },
  home_flood_sub: { bn: "এখন কী করবেন", en: "What to do now" },
  home_cases: { bn: "আমার রেকর্ড", en: "My saved cases" },
  home_cases_sub: { bn: "আগের ফলাফল আর পাঠানো", en: "Past results and sharing" },
  home_saao: { bn: "কৃষি অফিসারের ড্যাশবোর্ড", en: "SAAO dashboard" },
  home_profile_empty: { bn: "আপনার জমির তথ্য দিন (একবারই)", en: "Add your farm details (once)" },
  home_profile_edit: { bn: "বদলান", en: "Edit" },
  // Shell
  offline_ok: { bn: "ইন্টারনেট ছাড়াই চলবে", en: "Works offline" },
  offline_checking: { bn: "পরীক্ষা চলছে…", en: "Checking…" },
  offline_missing: { bn: "অফলাইন প্রস্তুত নয়", en: "Not ready offline" },
  online: { bn: "অনলাইন", en: "Online" },
  no_net: { bn: "নেট নেই", en: "No internet" },
  nav_home: { bn: "হোম", en: "Home" },
  nav_check: { bn: "পাতা", en: "Leaf" },
  nav_flood: { bn: "বন্যা", en: "Flood" },
  nav_cases: { bn: "রেকর্ড", en: "Cases" },
  back: { bn: "পেছনে", en: "Back" },
  next: { bn: "পরের ধাপ", en: "Next" },
  skip: { bn: "বাদ দিন", en: "Skip" },
  dont_know: { bn: "জানি না", en: "Don't know" },
  yes: { bn: "হ্যাঁ", en: "Yes" },
  no: { bn: "না", en: "No" },
  save: { bn: "সংরক্ষণ করুন", en: "Save" },
  step_of: { bn: "ধাপ", en: "Step" },
  // Demo date
  demo_banner: { bn: "ডেমো: কাল্পনিক তারিখ", en: "Demo: simulated date" },
  demo_off: { bn: "আজকের তারিখে ফিরুন", en: "Use today" },
  demo_set: { bn: "ডেমো তারিখ", en: "Demo date" },
  // Profile
  profile_title: { bn: "আপনার জমি", en: "Your farm" },
  profile_sub: { bn: "মৌসুমে একবার দিলেই হবে। ফোনেই থাকে, কোথাও পাঠানো হয় না।", en: "Once per season. Stays on this phone, never sent." },
  profile_upazila: { bn: "উপজেলা", en: "Upazila" },
  profile_variety: { bn: "ধানের জাত", en: "Rice variety" },
  profile_season: { bn: "মৌসুম", en: "Season" },
  profile_transplant: { bn: "চারা রোপণের তারিখ", en: "Transplanting date" },
  profile_transplant_hint: { bn: "এটা থেকে ধানের বয়স হিসাব হয়", en: "Used to estimate the crop stage" },
  season_aman: { bn: "আমন", en: "Aman" },
  season_aus: { bn: "আউশ", en: "Aus" },
  season_boro: { bn: "বোরো", en: "Boro" },
  // Stages
  stage: { bn: "ধানের অবস্থা", en: "Crop stage" },
  stage_estimated: { bn: "রোপণের তারিখ থেকে আন্দাজ — ঠিক না হলে বদলান", en: "Estimated from transplant date — change if wrong" },
  stage_seedbed: { bn: "বীজতলা", en: "Seedbed" },
  stage_early_tillering: { bn: "সদ্য রোপণ", en: "Just transplanted" },
  stage_tillering: { bn: "কুশি গজানো", en: "Tillering" },
  stage_pi_booting: { bn: "থোড় আসা", en: "Booting" },
  stage_flowering: { bn: "ফুল আসা", en: "Flowering" },
  stage_grain_filling: { bn: "দানা পুষ্ট হওয়া", en: "Grain filling" },
  // Leaf check
  check_title: { bn: "পাতা পরীক্ষা", en: "Leaf check" },
  photo_title: { bn: "একটা অসুস্থ পাতার ছবি তুলুন", en: "Photograph one sick leaf" },
  photo_tips: { bn: "দিনের আলোয়, কাছ থেকে, শুধু একটা পাতা। ছবি ঝাপসা যেন না হয়।", en: "Daylight, close up, one leaf only. Keep it sharp." },
  photo_camera: { bn: "ক্যামেরা খুলুন", en: "Open camera" },
  photo_gallery: { bn: "গ্যালারি থেকে নিন", en: "Choose from gallery" },
  photo_retake: { bn: "আবার তুলুন", en: "Retake" },
  photo_not_image: { bn: "এটা ছবি নয়। একটা পাতার ছবি বাছুন।", en: "That is not a photo. Please pick a leaf photo." },
  photo_failed: { bn: "ছবিটা খোলা গেল না। আবার তুলুন বা গ্যালারি থেকে নিন।", en: "Could not open this photo. Take it again or pick from the gallery." },
  camera_guide: { bn: "একটা পাতা ফ্রেমের মধ্যে রাখুন, তারপর বড় বোতাম চাপুন", en: "Fit one leaf inside the frame, then press the big button" },
  camera_shoot: { bn: "ছবি তুলুন", en: "Take photo" },
  photo_drop: { bn: "অথবা ছবি টেনে এনে এখানে ছাড়ুন", en: "or drag a photo here" },
  photo_reading: { bn: "পাতা দেখা হচ্ছে…", en: "Looking at the leaf…" },
  photo_saved_local: { bn: "ছবি শুধু এই ফোনে রাখা হয়েছে", en: "Photo kept on this phone only" },
  pick_many: { bn: "একাধিক বাছতে পারেন", en: "You can pick more than one" },
  field_title: { bn: "এই জমি সম্পর্কে", en: "About this field" },
  field_sub: { bn: "আগে দেওয়া থাকলে নিজে থেকেই ভরা থাকবে। ভুল হলে বদলান।", en: "Filled in from last time. Change it if it's wrong." },
  variety_hint: { bn: "না জানলে \"স্থানীয় / জানি না\" বাছুন", en: "Pick \"Local / don't know\" if unsure" },
  need_both: { bn: "দুটোই বাছুন, তারপর পরের ধাপে যান", en: "Choose both, then go next" },
  pest_note_title: { bn: "আপনি পোকার কথা বলেছেন", en: "You reported insects" },
  pest_note: {
    bn: "পাতার ছবি দেখে এই অ্যাপ পোকার ক্ষতি বিচার করতে পারে না। এই পোকাগুলোর কথা কৃষি অফিসারকে জানান:",
    en: "This app cannot judge insect damage from a leaf photo. Tell your SAAO about these insects:",
  },
  q_where: { bn: "সমস্যাটা গাছের কোথায়?", en: "Where on the plant is the problem?" },
  where_tip_edge: { bn: "পাতার আগা বা কিনারা", en: "Leaf tip or edge" },
  where_middle: { bn: "পাতার মাঝখানে", en: "Middle of the leaf" },
  where_sheath: { bn: "পানির কাছে কাণ্ডে", en: "Stem near the water" },
  where_panicle: { bn: "শীষে বা শীষের গোড়ায়", en: "Panicle or its neck" },
  where_base: { bn: "গাছের গোড়ায়", en: "Base of the plant" },
  q_pattern: { bn: "জমিতে কতটা জায়গায়?", en: "How much of the field?" },
  pattern_one_hill: { bn: "এক-দুই গোছায়", en: "One or two hills" },
  pattern_patches: { bn: "জায়গায় জায়গায়", en: "In patches" },
  pattern_whole_field: { bn: "পুরো জমিতে", en: "Whole field" },
  pattern_whole_field_dying: { bn: "পুরো জমি শুকিয়ে মরছে", en: "Whole field drying and dying" },
  q_first: { bn: "কোন পাতায় আগে শুরু?", en: "Which leaves first?" },
  first_old: { bn: "নিচের পুরনো পাতা", en: "Old lower leaves" },
  first_new: { bn: "উপরের নতুন পাতা", en: "Young top leaves" },
  q_insects: { bn: "কোনো পোকা দেখেছেন?", en: "Any insects?" },
  insects_none: { bn: "কোনো পোকা দেখিনি", en: "No insects seen" },
  // Insects: local name + what it looks like (farmers know these by name). Claude draft — Zoha check local names.
  ins_green_leafhopper: { bn: "সবুজ পাতাফড়িং", en: "Green leafhopper" },
  ins_green_leafhopper_h: { bn: "পাতায় ছোট সবুজ লাফানো পোকা", en: "Small green jumping insect on leaves" },
  ins_bph: { bn: "বাদামি গাছফড়িং (কারেন্ট পোকা)", en: "Brown planthopper" },
  ins_bph_h: { bn: "গোড়ায় পানির কাছে অনেক ছোট বাদামি পোকা", en: "Many small brown insects at the base, near the water" },
  ins_wbph: { bn: "সাদা-পিঠ গাছফড়িং", en: "White-backed planthopper" },
  ins_wbph_h: { bn: "গোড়ায় পিঠে সাদা দাগওয়ালা ছোট পোকা", en: "Small insects with a white stripe on the back, at the base" },
  ins_stem_borer: { bn: "মাজরা পোকা", en: "Stem borer" },
  ins_stem_borer_h: { bn: "মাঝের ডগা মরা, বা সাদা খালি শীষ", en: "Dead centre shoot, or white empty panicle" },
  ins_hispa: { bn: "পামরি পোকা", en: "Rice hispa" },
  ins_hispa_h: { bn: "কালো কাঁটাওয়ালা পোকা, পাতায় সাদা আঁচড়", en: "Black spiny beetle, white scratches on leaves" },
  ins_leaf_folder: { bn: "পাতা মোড়ানো পোকা", en: "Leaf folder" },
  ins_leaf_folder_h: { bn: "পাতা লম্বালম্বি মোড়ানো, ভেতরে সবুজ শুঁয়োপোকা", en: "Leaf rolled lengthwise, green caterpillar inside" },
  ins_rice_bug: { bn: "গান্ধি পোকা", en: "Rice bug (gandhi bug)" },
  ins_rice_bug_h: { bn: "দুর্গন্ধওয়ালা লম্বা পোকা, দুধ-দানা চুষে খায়", en: "Long, bad-smelling bug that sucks milky grains" },
  ins_armyworm: { bn: "লেদা পোকা / শীষকাটা লেদা", en: "Armyworm / cutworm" },
  ins_armyworm_h: { bn: "শুঁয়োপোকা পাতা বা শীষ কেটে খায়", en: "Caterpillars cut and eat leaves or panicles" },
  ins_gall_midge: { bn: "গলমাছি", en: "Gall midge" },
  ins_gall_midge_h: { bn: "পাতার বদলে পেঁয়াজ পাতার মতো নল বের হয়", en: "An onion-leaf-like tube grows instead of a leaf" },
  ins_grasshopper: { bn: "ঘাসফড়িং", en: "Grasshopper" },
  ins_grasshopper_h: { bn: "বড় লাফানো পোকা, পাতার কিনারা খায়", en: "Big jumping insect, eats leaf edges" },
  q_weather: { bn: "গত ৭ দিনে আবহাওয়া", en: "Weather in the last 7 days" },
  q_rain: { bn: "বৃষ্টি", en: "Rain" },
  rain_none: { bn: "হয়নি", en: "None" },
  rain_some: { bn: "কিছু", en: "Some" },
  rain_heavy: { bn: "অনেক", en: "Heavy" },
  q_flooded: { bn: "জমিতে বন্যার পানি উঠেছিল?", en: "Was the field flooded?" },
  q_storm: { bn: "ঝড় বা জোর বাতাস?", en: "Storm or strong wind?" },
  q_cold: { bn: "রাতে খুব ঠান্ডা?", en: "Very cold nights?" },
  q_salty: { bn: "লোনা বা জোয়ারের পানি ঢুকেছিল?", en: "Salty or tidal water came in?" },
  q_urea: { bn: "সম্প্রতি ইউরিয়া দিয়েছেন?", en: "Urea recently?" },
  urea_none: { bn: "দিইনি", en: "None" },
  urea_normal: { bn: "স্বাভাবিক", en: "Normal" },
  urea_a_lot: { bn: "অনেক বেশি", en: "A lot" },
  see_result: { bn: "ফলাফল দেখুন", en: "See the result" },
  // Flood
  flood_title: { bn: "বন্যা বা খরার পরে", en: "After flood or drought" },
  q_event: { bn: "কী হয়েছে?", en: "What happened?" },
  event_flood: { bn: "বন্যা", en: "Flood" },
  event_drought: { bn: "খরা / শুকনো", en: "Drought / dry spell" },
  q_variety_type: { bn: "আপনার ধান কি বন্যা-সহনশীল জাত?", en: "Is your rice a flood-tolerant variety?" },
  variety_sub1_hint: { bn: "ব্রি ধান৫১, ৫২, ৭৯, বিনা ধান১১, ১২", en: "BRRI dhan51, 52, 79, BINA dhan11, 12" },
  q_submergence: { bn: "গাছ কতটা পানির নিচে ছিল?", en: "How deep was the water?" },
  sub_full: { bn: "পুরো গাছ ডুবে ছিল", en: "Whole plant under water" },
  sub_partial: { bn: "পাতার আগা পানির উপরে ছিল", en: "Leaf tips above water" },
  q_days: { bn: "কত দিন পানির নিচে ছিল?", en: "How many days under water?" },
  days: { bn: "দিন", en: "days" },
  q_hills: { bn: "পানি নামার পরে কতগুলো গোছা বেঁচে আছে?", en: "After the water went, how many hills are alive?" },
  q_hills_hint: { bn: "পানি নামার ৫-৭ দিন পরে দেখুন। এখনো না দেখলে বাদ দিন।", en: "Check 5–7 days after the water goes. Skip if not checked yet." },
  hills_most: { bn: "বেশিরভাগ", en: "Most" },
  hills_about_half: { bn: "প্রায় অর্ধেক", en: "About half" },
  hills_few: { bn: "খুব কম", en: "Very few" },
  q_seedlings: { bn: "চারা জোগাড় করতে পারবেন?", en: "Can you get seedlings?" },
  q_date: { bn: "কোন তারিখের জন্য পরামর্শ?", en: "Advice for which date?" },
  date_today: { bn: "আজ", en: "Today" },
  region_from_profile: { bn: "এলাকা আপনার জমির তথ্য থেকে নেওয়া", en: "Area taken from your farm details" },
  // Result
  result_title: { bn: "ফলাফল", en: "Result" },
  listen: { bn: "শুনুন", en: "Listen" },
  stop: { bn: "থামান", en: "Stop" },
  audio_missing: { bn: "এই অংশের অডিও এখনো রেকর্ড হয়নি", en: "Audio for this card is not recorded yet" },
  how_sure: { bn: "কতটা নিশ্চিত", en: "How sure" },
  not_certain: { bn: "নিশ্চিত নয়", en: "not certain" },
  conf_low: { bn: "কম", en: "Low" },
  conf_mid: { bn: "মাঝারি", en: "Medium" },
  conf_high: { bn: "বেশি", en: "Higher" },
  part_see: { bn: "যা দেখছি", en: "What we see" },
  part_why: { bn: "কতটা নিশ্চিত, কেন", en: "How sure and why" },
  part_do: { bn: "এখন করুন", en: "Do now" },
  part_dont: { bn: "করবেন না", en: "Do not" },
  part_spray: { bn: "ওষুধের কথা", en: "About spraying" },
  part_ask: { bn: "মানুষকে জিজ্ঞেস করুন", en: "Ask a person" },
  check_more: { bn: "আরো নিশ্চিত হতে নিজে দেখুন", en: "To be more sure, check this yourself" },
  why_title: { bn: "কেন এই উত্তর", en: "Why this answer" },
  why_inputs: { bn: "আপনার উত্তর", en: "Your answers" },
  why_rule: { bn: "নিয়ম", en: "Rule" },
  why_sources: { bn: "উৎস", en: "Sources" },
  why_model: { bn: "ছবির মডেল", en: "Photo model" },
  why_context: { bn: "আপনার তথ্য দিয়ে যাচাই", en: "Checked against your answers" },
  dummy_model: { bn: "পরীক্ষামূলক ডামি মডেল — ফলাফল অর্থহীন", en: "DUMMY test model — results are meaningless" },
  date_used: { bn: "ব্যবহৃত তারিখ", en: "Date used" },
  simulated: { bn: "কাল্পনিক (ডেমো)", en: "simulated (demo)" },
  share_title: { bn: "কৃষি অফিসারকে পাঠাবেন?", en: "Share with your SAAO?" },
  share_body: { bn: "শুধু এই ফলাফল, আপনার উত্তর আর উপজেলা পাঠানো হবে। নাম বা লোকেশন যাবে না। আপনি হ্যাঁ না বললে কিছুই ফোন থেকে বের হবে না।", en: "Only this result, your answers and your upazila are sent. No name, no location. Nothing leaves the phone unless you tap yes." },
  share_photo: { bn: "ছবিটাও পাঠান (ছোট করে)", en: "Also send the photo (small)" },
  share_yes: { bn: "হ্যাঁ, পাঠান", en: "Yes, share" },
  share_no: { bn: "না, থাক", en: "No, keep it" },
  share_btn: { bn: "কৃষি অফিসারকে পাঠান", en: "Share with my SAAO" },
  share_queued: { bn: "রাখা হয়েছে। নেট পেলে কৃষি অফিসারের কাছে যাবে।", en: "Saved. It will be sent to your SAAO when there is a connection." },
  share_synced: { bn: "কৃষি অফিসারের কাছে পাঠানো হয়েছে", en: "Sent to your SAAO" },
  new_check: { bn: "নতুন পরীক্ষা", en: "New check" },
  go_home: { bn: "হোমে যান", en: "Home" },
  // Voice
  speak_question: { bn: "প্রশ্নটা শুনুন", en: "Listen to the question" },
  voice_title: { bn: "নিজের কথায় কৃষি অফিসারকে বলুন", en: "Tell your SAAO in your own words" },
  voice_hint: {
    bn: "৩০ সেকেন্ড পর্যন্ত বলতে পারেন। রেকর্ড শুধু এই ফোনে থাকে, আপনি পাঠাতে চাইলে তবেই যাবে।",
    en: "Up to 30 seconds. The recording stays on this phone and is only sent if you choose to share it.",
  },
  voice_record: { bn: "রেকর্ড শুরু করুন", en: "Start recording" },
  voice_stop: { bn: "থামান", en: "Stop" },
  voice_again: { bn: "আবার রেকর্ড করুন", en: "Record again" },
  voice_delete: { bn: "মুছে দিন", en: "Delete" },
  voice_saved: { bn: "আপনার কথা রাখা হয়েছে", en: "Your voice note is saved" },
  voice_no_mic: { bn: "মাইক্রোফোন চালু করা যায়নি। ফোনের সেটিংসে অনুমতি দিন।", en: "Could not use the microphone. Allow it in the phone settings." },
  share_voice: { bn: "আমার কথার রেকর্ডও পাঠান", en: "Also send my voice note" },
  saao_voice: { bn: "কৃষকের কথা", en: "Farmer's voice note" },
  // Area update (only with internet)
  area_title: { bn: "আপনার এলাকার সর্বশেষ খবর", en: "Latest for your area" },
  area_offline: { bn: "ইন্টারনেট পেলে আপনার এলাকার বন্যা, বৃষ্টি আর দামের খবর এখানে দেখাবে", en: "With internet, flood, rain and price news for your area appears here" },
  area_loading: { bn: "এলাকার খবর আনা হচ্ছে…", en: "Getting area news…" },
  area_none: { bn: "এই মুহূর্তে এলাকার খবর পাওয়া যায়নি", en: "No area update available right now" },
  area_rain_past: { bn: "গত ১০ দিনের বৃষ্টি", en: "Rain, last 10 days" },
  area_rain_next: { bn: "আগামী ৩ দিন", en: "Next 3 days" },
  area_price: { bn: "ধানের দাম", en: "Paddy price" },
  maund: { bn: "মণ", en: "maund" },
  trend_rising: { bn: "বাড়ছে", en: "rising" },
  trend_steady: { bn: "স্থির", en: "steady" },
  trend_falling: { bn: "কমছে", en: "falling" },
  // Cases
  cases_title: { bn: "আমার রেকর্ড", en: "My saved cases" },
  cases_empty: { bn: "এখনো কোনো রেকর্ড নেই", en: "No cases yet" },
  sync_now: { bn: "এখন পাঠান", en: "Sync now" },
  syncing: { bn: "পাঠানো হচ্ছে…", en: "Syncing…" },
  status_local: { bn: "শুধু ফোনে", en: "Phone only" },
  status_queued: { bn: "পাঠানোর অপেক্ষায়", en: "Waiting to send" },
  status_synced: { bn: "পাঠানো হয়েছে", en: "Sent" },
  status_failed: { bn: "পাঠানো যায়নি, আবার চেষ্টা হবে", en: "Not sent, will retry" },
  sync_result: { bn: "পাঠানো হয়েছে", en: "sent" },
  sync_offline: { bn: "নেট নেই — পরে আবার চেষ্টা হবে", en: "No connection — will retry later" },
  delete_all: { bn: "সব মুছুন", en: "Delete all" },
  delete_confirm: { bn: "এই ফোনের সব রেকর্ড মুছে যাবে। নিশ্চিত?", en: "This deletes every case on this phone. Sure?" },
  // SAAO
  saao_title: { bn: "কৃষি অফিসারের ড্যাশবোর্ড", en: "SAAO dashboard" },
  saao_sub: { bn: "কৃষকেরা যে কেস পাঠিয়েছেন", en: "Cases farmers chose to share" },
  saao_backend_down: { bn: "সার্ভারে পৌঁছানো যায়নি — ডেমোর জন্য সাজানো কেস দেখানো হচ্ছে", en: "Server not reachable — showing seeded demo cases" },
  seeded: { bn: "সাজানো (ডেমো)", en: "seeded (demo)" },
  sms_title: { bn: "কিপ্যাড ফোনে এসএমএস", en: "SMS to a keypad phone" },
  sms_simulated: { bn: "কাল্পনিক — কোনো এসএমএস পাঠানো হয়নি", en: "Simulated — no SMS is sent" },
  received: { bn: "পেয়েছেন", en: "Received" },
  filter_all: { bn: "সব", en: "All" },
  filter_unsure: { bn: "নিশ্চিত নয়", en: "Not sure" },
  refresh: { bn: "রিফ্রেশ", en: "Refresh" },
  // Offline self-check
  selfcheck_title: { bn: "অফলাইন পরীক্ষা", en: "Offline self-check" },
  selfcheck_ok: { bn: "সব ফাইল ফোনে আছে। ইন্টারনেট ছাড়াই চলবে।", en: "Every file is on the phone. Works without internet." },
  selfcheck_dev: { bn: "ডেভেলপমেন্ট মোডে অফলাইন বন্ধ থাকে", en: "Offline caching is off in development mode" },
} as const;

export type StringKey = keyof typeof S;
