// Every UI string, Bangla first. Bangla = CLAUDE DRAFT: Zoha reviews every line (keep it everyday village Bangla).
// Card texts live in public/data/cards.json; follow-up questions in public/data/knowledge.json.

export const APP_NAME = { bn: "ধানসাথী", en: "DhanSathi" };

export const S = {
  tagline: { bn: "ধানের পাতা আর বন্যার পরামর্শ — ইন্টারনেট ছাড়াই", en: "Rice leaf and flood advice — no internet needed" },
  // Home
  home_check: { bn: "পাতা পরীক্ষা করুন", en: "Check a leaf" },
  home_check_sub: { bn: "ধানপাতার ছবি তুলুন", en: "Take a photo of a rice leaf" },
  home_flood: { bn: "বন্যা বা খরার পরে", en: "After flood or drought" },
  home_flood_sub: { bn: "এখন কী করবেন", en: "What to do now" },
  home_cases: { bn: "আমার রেকর্ড", en: "My saved cases" },
  home_cases_sub: { bn: "আগের ফলাফল আর পাঠানো", en: "Past results and sharing" },
  home_saao: { bn: "কৃষি অফিসারের ড্যাশবোর্ড", en: "SAAO dashboard" },
  home_profile_empty: { bn: "আপনার জমির তথ্য দিন (একবারই)", en: "Add your farm details (once)" },
  home_profile_edit: { bn: "বদলান", en: "Edit" },
  // Shell
  offline_ok: { bn: "ইন্টারনেট ছাড়াই চলবে", en: "Works offline" },
  offline_checking: { bn: "পরীক্ষা চলছে…", en: "Checking…" },
  offline_missing: { bn: "অফলাইন প্রস্তুত নয়", en: "Not ready offline" },
  online: { bn: "অনলাইন", en: "Online" },
  no_net: { bn: "নেট নেই", en: "No internet" },
  nav_home: { bn: "হোম", en: "Home" },
  nav_check: { bn: "পাতা", en: "Leaf" },
  nav_flood: { bn: "বন্যা", en: "Flood" },
  nav_cases: { bn: "রেকর্ড", en: "Cases" },
  back: { bn: "পেছনে", en: "Back" },
  next: { bn: "পরের ধাপ", en: "Next" },
  skip: { bn: "বাদ দিন", en: "Skip" },
  change: { bn: "বদলান", en: "Change" },
  your_field: { bn: "আপনার জমি", en: "Your field" },
  followup_title: { bn: "আর দু-একটা প্রশ্ন", en: "A couple more questions" },
  // Claude draft for Zoha: says why we ask, that it is the last step, and that "জানি না" is fine.
  followup_sub: { bn: "ছবি দেখে দুটো সমস্যার কোনটা তা পরিষ্কার নয়। শেষ এই ২-৩টা উত্তর দিলে পরামর্শ আরও ঠিক হবে। না জানলে \"জানি না\" চাপুন।", en: "The photo alone can't tell which of two problems it is. Last 2–3 answers make the advice more accurate. Not sure? Tap \"Don't know\"." },
  db_blocked: { bn: "অ্যাপটি অন্য একটি ট্যাব বা উইন্ডোতেও খোলা আছে — সেটি বন্ধ করে আবার চেষ্টা করুন", en: "The app is also open in another tab or window — close it and try again" },
  photo_not_saved: { bn: "ছবিটা ফোনে রাখা যায়নি, তবু পরীক্ষা চলছে", en: "Couldn't keep the photo on the phone, but the check continues" },
  // Claude draft (Zoha to check): model loading stages and failure
  stage_script: { bn: "ইঞ্জিন চালু হচ্ছে…", en: "Starting the engine…" },
  stage_files: { bn: "মডেল লোড হচ্ছে (প্রথমবার একটু সময় লাগে)…", en: "Loading the model (takes longer the first time)…" },
  stage_session: { bn: "প্রস্তুত হচ্ছে…", en: "Getting ready…" },
  stage_warmup: { bn: "প্রায় তৈরি…", en: "Almost ready…" },
  stage_ready: { bn: "ছবি পড়া হচ্ছে…", en: "Reading the photo…" },
  model_failed: { bn: "ছবিটা পড়া গেল না", en: "Couldn't read the photo" },
  try_again: { bn: "আবার চেষ্টা করুন", en: "Try again" },
  change_answers: { bn: "উত্তর বদলান", en: "Change answers" },
  dont_know: { bn: "জানি না", en: "Don't know" },
  yes: { bn: "হ্যাঁ", en: "Yes" },
  no: { bn: "না", en: "No" },
  save: { bn: "সংরক্ষণ করুন", en: "Save" },
  step_of: { bn: "ধাপ", en: "Step" },
  // Demo date
  demo_banner: { bn: "ডেমো: কাল্পনিক তারিখ", en: "Demo: simulated date" },
  demo_off: { bn: "আজকের তারিখে ফিরুন", en: "Use today" },
  demo_set: { bn: "ডেমো তারিখ", en: "Demo date" },
  // Profile
  profile_title: { bn: "আপনার জমি", en: "Your farm" },
  profile_sub: { bn: "মৌসুমে একবার দিলেই হবে। ফোনেই থাকে, কোথাও পাঠানো হয় না।", en: "Once per season. Stays on this phone, never sent." },
  profile_upazila: { bn: "উপজেলা", en: "Upazila" },
  profile_district: { bn: "জেলা", en: "District" },
  district_first: { bn: "আগে জেলা বাছুন", en: "Choose the district first" },
  vg_unknown: { bn: "জানি না", en: "Don't know" },
  vg_flood: { bn: "বন্যা-সহনশীল জাত", en: "Flood-tolerant varieties" },
  vg_brri: { bn: "বিআর / ব্রি ধান", en: "BR / BRRI dhan" },
  vg_bina: { bn: "বিনা ধান", en: "BINA dhan" },
  vg_hybrid: { bn: "হাইব্রিড", en: "Hybrid" },
  vg_local: { bn: "স্থানীয় জাত", en: "Local varieties" },
  vg_other: { bn: "অন্য", en: "Other" },
  profile_variety: { bn: "ধানের জাত", en: "Rice variety" },
  profile_season: { bn: "মৌসুম", en: "Season" },
  profile_transplant: { bn: "চারা রোপণের তারিখ", en: "Transplanting date" },
  profile_transplant_hint: { bn: "এটা থেকে ধানের বয়স হিসাব হয়", en: "Used to estimate the crop stage" },
  season_aman: { bn: "আমন", en: "Aman" },
  season_aus: { bn: "আউশ", en: "Aus" },
  season_boro: { bn: "বোরো", en: "Boro" },
  // Stages
  stage: { bn: "ধানের অবস্থা", en: "Crop stage" },
  stage_estimated: { bn: "রোপণের তারিখ থেকে আন্দাজ — ঠিক না হলে বদলান", en: "Estimated from transplant date — change if wrong" },
  stage_seedbed: { bn: "বীজতলা", en: "Seedbed" },
  stage_early_tillering: { bn: "সদ্য রোপণ", en: "Just transplanted" },
  stage_tillering: { bn: "কুশি গজানো", en: "Tillering" },
  stage_pi_booting: { bn: "থোড় আসা", en: "Booting" },
  stage_flowering: { bn: "ফুল আসা", en: "Flowering" },
  stage_grain_filling: { bn: "দানা পুষ্ট হওয়া", en: "Grain filling" },
  // Leaf check
  check_title: { bn: "পাতা পরীক্ষা", en: "Leaf check" },
  photo_title: { bn: "একটা অসুস্থ পাতার ছবি তুলুন", en: "Photograph one sick leaf" },
  photo_tips: { bn: "দিনের আলোয়, কাছ থেকে, শুধু একটা পাতা। ছবি ঝাপসা যেন না হয়।", en: "Daylight, close up, one leaf only. Keep it sharp." },
  photo_camera: { bn: "ক্যামেরা খুলুন", en: "Open camera" },
  photo_gallery: { bn: "গ্যালারি থেকে নিন", en: "Choose from gallery" },
  photo_retake: { bn: "আবার তুলুন", en: "Retake" },
  photo_not_image: { bn: "এটা ছবি নয়। একটা পাতার ছবি বাছুন।", en: "That is not a photo. Please pick a leaf photo." },
  photo_failed: { bn: "ছবিটা খোলা গেল না। আবার তুলুন বা গ্যালারি থেকে নিন।", en: "Could not open this photo. Take it again or pick from the gallery." },
  camera_guide: { bn: "একটা পাতা ফ্রেমের মধ্যে রাখুন, তারপর বড় বোতাম চাপুন", en: "Fit one leaf inside the frame, then press the big button" },
  camera_shoot: { bn: "ছবি তুলুন", en: "Take photo" },
  photo_drop: { bn: "অথবা ছবি টেনে এনে এখানে ছাড়ুন", en: "or drag a photo here" },
  photo_reading: { bn: "পাতা দেখা হচ্ছে…", en: "Looking at the leaf…" },
  photo_add: { bn: "আরেকটা ছবি", en: "Add photo" },
  photo_add_hint: { bn: "চাইলে আরো ২টা অসুস্থ পাতার ছবি দিন। বেশি ছবিতে উত্তর আরো ভরসাযোগ্য হয়।", en: "Optional: add up to 2 more photos of other sick leaves. More photos make the answer more reliable." },
  photo_add_camera: { bn: "ক্যামেরা", en: "Camera" },
  photo_add_gallery: { bn: "গ্যালারি", en: "Gallery" },
  why_photos: { bn: "প্রতিটা ছবিতে মডেল যা দেখেছে", en: "What the model saw in each photo" },
  photo_saved_local: { bn: "ছবি শুধু এই ফোনে রাখা হয়েছে", en: "Photo kept on this phone only" },
  pick_many: { bn: "একাধিক বাছতে পারেন", en: "You can pick more than one" },
  field_title: { bn: "এই জমি সম্পর্কে", en: "About this field" },
  field_sub: { bn: "আগে দেওয়া থাকলে নিজে থেকেই ভরা থাকবে। ভুল হলে বদলান।", en: "Filled in from last time. Change it if it's wrong." },
  variety_hint: { bn: "না জানলে \"স্থানীয় / জানি না\" বাছুন", en: "Pick \"Local / don't know\" if unsure" },
  need_both: { bn: "দুটোই বাছুন, তারপর পরের ধাপে যান", en: "Choose both, then go next" },
  pest_note_title: { bn: "আপনি পোকার কথা বলেছেন", en: "You reported insects" },
  pest_note: {
    bn: "পাতার ছবি দেখে এই অ্যাপ পোকার ক্ষতি বিচার করতে পারে না। এই পোকাগুলোর কথা কৃষি অফিসারকে জানান:",
    en: "This app cannot judge insect damage from a leaf photo. Tell your SAAO about these insects:",
  },
  q_where: { bn: "সমস্যাটা গাছের কোথায়?", en: "Where on the plant is the problem?" },
  where_tip_edge: { bn: "পাতার আগা বা কিনারা", en: "Leaf tip or edge" },
  where_middle: { bn: "পাতার মাঝখানে", en: "Middle of the leaf" },
  where_sheath: { bn: "পানির কাছে কাণ্ডে", en: "Stem near the water" },
  where_panicle: { bn: "শীষে বা শীষের গোড়ায়", en: "Panicle or its neck" },
  where_base: { bn: "গাছের গোড়ায়", en: "Base of the plant" },
  where_whole_plant: { bn: "পুরো গাছে (পাতা, কাণ্ড, সব জায়গায়)", en: "The whole plant (leaves, stem, everywhere)" },
  where_grain: { bn: "দানায় বা ধানের খোসায়", en: "On the grains (husk)" },
  q_mould: { bn: "পাতায় বা গাছে কি ছাতা, ঝুল বা পাউডার আছে? কোন রঙের?", en: "Is there mould, fuzz or powder? What colour?" },
  q_mould_hint: { bn: "আঙুল দিয়ে আলতো ঘষে দেখুন", en: "Rub gently with a finger" },
  mould_white: { bn: "সাদা, তুলার মতো (পানির কাছে কাণ্ডে)", en: "White, cotton-like (on the stem near water)" },
  mould_grey: { bn: "ছাই রঙের পাউডার, দাগের মাঝখানে", en: "Grey powder in the middle of spots" },
  mould_black: { bn: "কালো ঝুল, ঘষলে উঠে যায়", en: "Black soot that rubs off" },
  mould_orange: { bn: "দানায় কমলা বা সবুজ-কালো বল", en: "Orange or green-black balls on the grains" },
  mould_none: { bn: "কোনো ছাতা বা ঝুল নেই", en: "No mould" },
  mould_note_title: { bn: "কালো ঝুল দেখেছেন", en: "You saw black sooty mould" },
  mould_note: { bn: "কালো ঝুল সাধারণত রস-চোষা পোকার (যেমন বাদামি গাছফড়িং) আঠালো মধুরসের উপর জন্মায়। গাছের গোড়ায় পোকা আছে কিনা দেখুন, আর কৃষি অফিসারকে জানান।", en: "Black sooty mould usually grows on the sticky honeydew of sucking insects such as brown planthopper. Check the plant base for insects and tell your SAAO." },
  library_title: { bn: "ধানের রোগ ও সমস্যা", en: "Rice problem guide" },
  library_sub: { bn: "কারণ অনুযায়ী সাজানো, কোনটা দেখতে কেমন", en: "Sorted by cause, how each one looks" },
  library_link: { bn: "রোগের তালিকায় দেখুন", en: "See it in the problem guide" },
  q_look: { bn: "সমস্যাটা দেখতে কেমন?", en: "What does the problem look like?" },
  q_look_hint: { bn: "যেটা সবচেয়ে মেলে সেটা বাছুন। ছবি দেখে সম্ভাব্যগুলো উপরে রাখা হয়েছে।", en: "Pick the closest. The likeliest ones from your photo are on top." },
  look_eye: { bn: "চোখের মতো দাগ, দুই মাথা সরু, মাঝখান ছাই রং", en: "Eye-shaped spots, pointed ends, grey centre" },
  look_round: { bn: "ছোট গোল বাদামি দাগ, অনেকগুলো", en: "Many small round brown spots" },
  look_stripe_tip_edge: { bn: "আগা বা কিনারা থেকে হলুদ-খড় রঙের লম্বা দাগ", en: "Yellow-straw stripes from the tip or edge" },
  look_thin_lines: { bn: "শিরার মাঝে সরু রেখা, রোদে ধরলে আলো দেখা যায়", en: "Thin lines between the veins, see-through against the sun" },
  look_bands: { bn: "আগা থেকে হালকা ও গাঢ় বাদামি ঢেউ", en: "Light and dark brown wavy bands from the tip" },
  look_stem_patch: { bn: "পানির কাছে কাণ্ডে ছাই-সবুজ ডিম্বাকার ছোপ", en: "Grey-green oval patches on the stem near water" },
  look_yellow_orange: { bn: "পাতা আগা থেকে হলদে-কমলা, গাছ খাটো", en: "Leaves yellow-orange from the tip, plants short" },
  look_dusty_rust: { bn: "কচি পাতায় মরিচার মতো ধুলোট বাদামি ছোপ", en: "Dusty rust-brown patches on young leaves" },
  look_brown_tips_old: { bn: "পুরনো পাতার আগা ও কিনারা বাদামি", en: "Brown tips and edges on old leaves" },
  look_bronze: { bn: "পাতা কমলা-বাদামি, তামাটে", en: "Orange-brown, bronze-coloured leaves" },
  look_pale: { bn: "পাতা ফ্যাকাশে হলুদ, কোনো দাগ নেই", en: "Pale yellow leaves, no spots" },
  look_none: { bn: "কোনো দাগ বা রং বদল নেই", en: "No spots or colour change" },
  told_title: { bn: "আপনি যা বলেছেন", en: "What you told us" },
  fit_title: { bn: "আপনার উত্তর কোনটার সাথে মেলে", en: "How your answers fit" },
  fit_against: { bn: "এর বিপক্ষে", en: "speaks against" },
  tips_title: { bn: "আপনার জমির জন্য এখন", en: "For your field now" },
  check_again_on: { bn: "আবার দেখুন", en: "Check again on" },
  this_week: { bn: "এই সপ্তাহে আপনার ফসলে", en: "This week for your crop" },
  where_none: { bn: "কোনো সমস্যা দেখছি না", en: "I don't see any problem" },
  q_pattern: { bn: "কয়টা গাছে এই সমস্যা?", en: "How many plants have this problem?" },
  q_pattern_hint: { bn: "জমির আইলে দাঁড়িয়ে একবার চারদিকে দেখুন", en: "Stand on the bund and look around the field once" },
  pattern_one_hill: { bn: "শুধু ১-২টা গাছে", en: "Only 1 or 2 plants" },
  pattern_patches: { bn: "জমির কয়েক জায়গায়, গোল গোল ছোপে", en: "A few spots in the field" },
  pattern_whole_field: { bn: "প্রায় সব গাছে, সমানভাবে", en: "Almost all plants, evenly" },
  pattern_whole_field_dying: { bn: "অনেক গাছ দ্রুত শুকিয়ে মরে যাচ্ছে", en: "Many plants are drying and dying fast" },
  pattern_whole_field_dying_h: { bn: "পানির অভাবে নয় (খরা হলে \"বন্যা বা খরা\" অংশে যান)", en: "Not from lack of water (for drought, use \"After flood or drought\")" },
  pattern_none: { bn: "কোনো গাছে সমস্যা নেই, শুধু দেখে নিতে চাই", en: "No sick plants, I just want a check" },
  q_first: { bn: "কোন পাতায় আগে শুরু?", en: "Which leaves first?" },
  first_old: { bn: "নিচের পুরনো পাতা", en: "Old lower leaves" },
  first_new: { bn: "উপরের নতুন পাতা", en: "Young top leaves" },
  first_none: { bn: "কোনো পাতায় সমস্যা নেই", en: "No leaves are affected" },
  q_insects: { bn: "কোনো পোকা দেখেছেন?", en: "Any insects?" },
  insects_none: { bn: "কোনো পোকা দেখিনি", en: "No insects seen" },
  // Insects: local name + what it looks like (farmers know these by name). Claude draft — Zoha check local names.
  ins_green_leafhopper: { bn: "সবুজ পাতাফড়িং", en: "Green leafhopper" },
  ins_green_leafhopper_h: { bn: "পাতায় ছোট সবুজ লাফানো পোকা", en: "Small green jumping insect on leaves" },
  ins_bph: { bn: "বাদামি গাছফড়িং (কারেন্ট পোকা)", en: "Brown planthopper" },
  ins_bph_h: { bn: "গোড়ায় পানির কাছে অনেক ছোট বাদামি পোকা", en: "Many small brown insects at the base, near the water" },
  ins_wbph: { bn: "সাদা-পিঠ গাছফড়িং", en: "White-backed planthopper" },
  ins_wbph_h: { bn: "গোড়ায় পিঠে সাদা দাগওয়ালা ছোট পোকা", en: "Small insects with a white stripe on the back, at the base" },
  ins_stem_borer: { bn: "মাজরা পোকা", en: "Stem borer" },
  ins_stem_borer_h: { bn: "মাঝের ডগা মরা, বা সাদা খালি শীষ", en: "Dead centre shoot, or white empty panicle" },
  ins_hispa: { bn: "পামরি পোকা", en: "Rice hispa" },
  ins_hispa_h: { bn: "কালো কাঁটাওয়ালা পোকা, পাতায় সাদা আঁচড়", en: "Black spiny beetle, white scratches on leaves" },
  ins_leaf_folder: { bn: "পাতা মোড়ানো পোকা", en: "Leaf folder" },
  ins_leaf_folder_h: { bn: "পাতা লম্বালম্বি মোড়ানো, ভেতরে সবুজ শুঁয়োপোকা", en: "Leaf rolled lengthwise, green caterpillar inside" },
  ins_rice_bug: { bn: "গান্ধি পোকা", en: "Rice bug (gandhi bug)" },
  ins_rice_bug_h: { bn: "দুর্গন্ধওয়ালা লম্বা পোকা, দুধ-দানা চুষে খায়", en: "Long, bad-smelling bug that sucks milky grains" },
  ins_armyworm: { bn: "লেদা পোকা / শীষকাটা লেদা", en: "Armyworm / cutworm" },
  ins_armyworm_h: { bn: "শুঁয়োপোকা পাতা বা শীষ কেটে খায়", en: "Caterpillars cut and eat leaves or panicles" },
  ins_gall_midge: { bn: "গলমাছি", en: "Gall midge" },
  ins_gall_midge_h: { bn: "পাতার বদলে পেঁয়াজ পাতার মতো নল বের হয়", en: "An onion-leaf-like tube grows instead of a leaf" },
  ins_grasshopper: { bn: "ঘাসফড়িং", en: "Grasshopper" },
  ins_grasshopper_h: { bn: "বড় লাফানো পোকা, পাতার কিনারা খায়", en: "Big jumping insect, eats leaf edges" },
  q_weather: { bn: "গত ৭ দিনে আবহাওয়া", en: "Weather in the last 7 days" },
  q_rain: { bn: "বৃষ্টি", en: "Rain" },
  rain_none: { bn: "হয়নি", en: "None" },
  rain_some: { bn: "কিছু", en: "Some" },
  rain_heavy: { bn: "অনেক", en: "Heavy" },
  q_flooded: { bn: "জমিতে বন্যার পানি উঠেছিল?", en: "Was the field flooded?" },
  q_storm: { bn: "ঝড় বা জোর বাতাস?", en: "Storm or strong wind?" },
  q_cold: { bn: "রাতে খুব ঠান্ডা?", en: "Very cold nights?" },
  q_salty: { bn: "লোনা বা জোয়ারের পানি ঢুকেছিল?", en: "Salty or tidal water came in?" },
  q_urea: { bn: "সম্প্রতি ইউরিয়া দিয়েছেন?", en: "Urea recently?" },
  urea_none: { bn: "দিইনি", en: "None" },
  urea_normal: { bn: "স্বাভাবিক", en: "Normal" },
  urea_a_lot: { bn: "অনেক বেশি", en: "A lot" },
  see_result: { bn: "ফলাফল দেখুন", en: "See the result" },
  // Flood
  flood_title: { bn: "বন্যা বা খরার পরে", en: "After flood or drought" },
  q_event: { bn: "কী হয়েছে?", en: "What happened?" },
  event_flood: { bn: "বন্যা", en: "Flood" },
  event_drought: { bn: "খরা / শুকনো", en: "Drought / dry spell" },
  q_variety_type: { bn: "আপনার ধান কি বন্যা-সহনশীল জাত?", en: "Is your rice a flood-tolerant variety?" },
  variety_sub1_hint: { bn: "ব্রি ধান৫১, ৫২, ৭৯, বিনা ধান১১, ১২", en: "BRRI dhan51, 52, 79, BINA dhan11, 12" },
  q_submergence: { bn: "গাছ কতটা পানির নিচে ছিল?", en: "How deep was the water?" },
  sub_full: { bn: "পুরো গাছ ডুবে ছিল", en: "Whole plant under water" },
  sub_partial: { bn: "পাতার আগা পানির উপরে ছিল", en: "Leaf tips above water" },
  q_days: { bn: "কত দিন পানির নিচে ছিল?", en: "How many days under water?" },
  days: { bn: "দিন", en: "days" },
  q_hills: { bn: "পানি নামার পরে কতগুলো গোছা বেঁচে আছে?", en: "After the water went, how many hills are alive?" },
  q_hills_hint: { bn: "পানি নামার ৫-৭ দিন পরে দেখুন। এখনো না দেখলে বাদ দিন।", en: "Check 5–7 days after the water goes. Skip if not checked yet." },
  hills_most: { bn: "বেশিরভাগ", en: "Most" },
  hills_about_half: { bn: "প্রায় অর্ধেক", en: "About half" },
  hills_few: { bn: "খুব কম", en: "Very few" },
  q_seedlings: { bn: "চারা জোগাড় করতে পারবেন?", en: "Can you get seedlings?" },
  q_date: { bn: "কোন তারিখের জন্য পরামর্শ?", en: "Advice for which date?" },
  date_today: { bn: "আজ", en: "Today" },
  region_from_profile: { bn: "এলাকা আপনার জমির তথ্য থেকে নেওয়া", en: "Area taken from your farm details" },
  // Result
  result_title: { bn: "ফলাফল", en: "Result" },
  listen: { bn: "শুনুন", en: "Listen" },
  stop: { bn: "থামান", en: "Stop" },
  audio_missing: { bn: "এই অংশের অডিও এখনো রেকর্ড হয়নি", en: "Audio for this card is not recorded yet" },
  how_sure: { bn: "কতটা নিশ্চিত", en: "How sure" },
  not_certain: { bn: "নিশ্চিত নয়", en: "not certain" },
  conf_low: { bn: "কম", en: "Low" },
  conf_mid: { bn: "মাঝারি", en: "Medium" },
  conf_high: { bn: "বেশি", en: "Higher" },
  part_see: { bn: "যা দেখছি", en: "What we see" },
  part_why: { bn: "কতটা নিশ্চিত, কেন", en: "How sure and why" },
  part_do: { bn: "এখন করুন", en: "Do now" },
  part_dont: { bn: "করবেন না", en: "Do not" },
  part_spray: { bn: "ওষুধের কথা", en: "About spraying" },
  part_ask: { bn: "মানুষকে জিজ্ঞেস করুন", en: "Ask a person" },
  check_more: { bn: "আরো নিশ্চিত হতে নিজে দেখুন", en: "To be more sure, check this yourself" },
  why_title: { bn: "কেন এই উত্তর", en: "Why this answer" },
  why_inputs: { bn: "আপনার উত্তর", en: "Your answers" },
  why_rule: { bn: "নিয়ম", en: "Rule" },
  why_sources: { bn: "উৎস", en: "Sources" },
  why_model: { bn: "ছবির মডেল", en: "Photo model" },
  why_context: { bn: "আপনার তথ্য দিয়ে যাচাই", en: "Checked against your answers" },
  dummy_model: { bn: "পরীক্ষামূলক ডামি মডেল — ফলাফল অর্থহীন", en: "DUMMY test model — results are meaningless" },
  date_used: { bn: "ব্যবহৃত তারিখ", en: "Date used" },
  simulated: { bn: "কাল্পনিক (ডেমো)", en: "simulated (demo)" },
  share_title: { bn: "কৃষি অফিসারকে পাঠাবেন?", en: "Share with your SAAO?" },
  share_body: { bn: "শুধু এই ফলাফল, আপনার উত্তর আর উপজেলা পাঠানো হবে। নাম বা লোকেশন যাবে না। আপনি হ্যাঁ না বললে কিছুই ফোন থেকে বের হবে না।", en: "Only this result, your answers and your upazila are sent. No name, no location. Nothing leaves the phone unless you tap yes." },
  share_photo: { bn: "ছবিটাও পাঠান (ছোট করে)", en: "Also send the photo (small)" },
  share_yes: { bn: "হ্যাঁ, পাঠান", en: "Yes, share" },
  share_no: { bn: "না, থাক", en: "No, keep it" },
  share_btn: { bn: "কৃষি অফিসারকে পাঠান", en: "Share with my SAAO" },
  share_queued: { bn: "রাখা হয়েছে। নেট পেলে কৃষি অফিসারের কাছে যাবে।", en: "Saved. It will be sent to your SAAO when there is a connection." },
  share_synced: { bn: "কৃষি অফিসারের কাছে পাঠানো হয়েছে", en: "Sent to your SAAO" },
  new_check: { bn: "নতুন পরীক্ষা", en: "New check" },
  go_home: { bn: "হোমে যান", en: "Home" },
  // Voice
  speak_question: { bn: "প্রশ্নটা শুনুন", en: "Listen to the question" },
  voice_title: { bn: "নিজের কথায় কৃষি অফিসারকে বলুন", en: "Tell your SAAO in your own words" },
  voice_hint: {
    bn: "৩০ সেকেন্ড পর্যন্ত বলতে পারেন। রেকর্ড শুধু এই ফোনে থাকে, আপনি পাঠাতে চাইলে তবেই যাবে।",
    en: "Up to 30 seconds. The recording stays on this phone and is only sent if you choose to share it.",
  },
  voice_record: { bn: "রেকর্ড শুরু করুন", en: "Start recording" },
  voice_stop: { bn: "থামান", en: "Stop" },
  voice_again: { bn: "আবার রেকর্ড করুন", en: "Record again" },
  voice_delete: { bn: "মুছে দিন", en: "Delete" },
  voice_saved: { bn: "আপনার কথা রাখা হয়েছে", en: "Your voice note is saved" },
  voice_no_mic: { bn: "মাইক্রোফোন চালু করা যায়নি। ফোনের সেটিংসে অনুমতি দিন।", en: "Could not use the microphone. Allow it in the phone settings." },
  share_voice: { bn: "আমার কথার রেকর্ডও পাঠান", en: "Also send my voice note" },
  saao_voice: { bn: "কৃষকের কথা", en: "Farmer's voice note" },
  // Crop calendar
  home_calendar: { bn: "ফসলের ক্যালেন্ডার", en: "Crop calendar" },
  home_calendar_sub: { bn: "এই সপ্তাহে কী করবেন, ভালো ফলনের জন্য", en: "What to do this week for a better harvest" },
  cal_title: { bn: "ফসলের ক্যালেন্ডার", en: "Crop calendar" },
  cal_need_date: { bn: "ক্যালেন্ডার দেখাতে চারা রোপণের তারিখ দিন", en: "Add the transplanting date to see your calendar" },
  cal_days: { bn: "রোপণের পর {n} দিন", en: "{n} days since transplanting" },
  cal_not_yet: { bn: "এখনো রোপণ হয়নি", en: "Not transplanted yet" },
  cal_do: { bn: "এই সময়ে যা করবেন", en: "What to do now" },
  cal_watch: { bn: "এই সময়ে যেগুলোর দিকে নজর রাখুন", en: "Watch out for" },
  cal_watch_hint: { bn: "সন্দেহ হলে পাতার ছবি তুলে পরীক্ষা করুন", en: "If in doubt, check a leaf photo" },
  cal_dates: { bn: "মৌসুমের জরুরি তারিখ", en: "Key dates this season" },
  cal_next: { bn: "পরের মৌসুমে ভালো ফলনের জন্য", en: "For a better harvest next season" },
  cal_estimate: { bn: "রোপণের তারিখ থেকে আন্দাজ, ১৪০ দিনের জাত ধরে। আপনার জাত আগে বা পরে পাকতে পারে।", en: "Estimated from the transplant date, assuming a ~140-day variety. Yours may be earlier or later." },
  cal_source: { bn: "উৎস", en: "Source" },
  cal_check_leaf: { bn: "পাতা পরীক্ষা করুন", en: "Check a leaf" },
  cal_from_healthy: { bn: "ভালো ফলনের জন্য আপনার ফসলের ক্যালেন্ডার দেখুন", en: "For a better harvest, see your crop calendar" },
  // Area update (only with internet)
  area_title: { bn: "আপনার এলাকার সর্বশেষ খবর", en: "Latest for your area" },
  area_offline: { bn: "ইন্টারনেট পেলে আপনার এলাকার বন্যা, বৃষ্টি আর দামের খবর এখানে দেখাবে", en: "With internet, flood, rain and price news for your area appears here" },
  area_loading: { bn: "এলাকার খবর আনা হচ্ছে…", en: "Getting area news…" },
  area_none: { bn: "এই মুহূর্তে এলাকার খবর পাওয়া যায়নি", en: "No area update available right now" },
  area_rain_past: { bn: "গত ১০ দিনের বৃষ্টি", en: "Rain, last 10 days" },
  area_rain_next: { bn: "আগামী ৩ দিন", en: "Next 3 days" },
  area_price: { bn: "ধানের দাম", en: "Paddy price" },
  maund: { bn: "মণ", en: "maund" },
  trend_rising: { bn: "বাড়ছে", en: "rising" },
  trend_steady: { bn: "স্থির", en: "steady" },
  trend_falling: { bn: "কমছে", en: "falling" },
  // Cases
  cases_title: { bn: "আমার রেকর্ড", en: "My saved cases" },
  cases_empty: { bn: "এখনো কোনো রেকর্ড নেই", en: "No cases yet" },
  sync_now: { bn: "এখন পাঠান", en: "Sync now" },
  syncing: { bn: "পাঠানো হচ্ছে…", en: "Syncing…" },
  status_local: { bn: "শুধু ফোনে", en: "Phone only" },
  status_queued: { bn: "পাঠানোর অপেক্ষায়", en: "Waiting to send" },
  status_synced: { bn: "পাঠানো হয়েছে", en: "Sent" },
  status_failed: { bn: "পাঠানো যায়নি, আবার চেষ্টা হবে", en: "Not sent, will retry" },
  sync_result: { bn: "পাঠানো হয়েছে", en: "sent" },
  sync_offline: { bn: "নেট নেই — পরে আবার চেষ্টা হবে", en: "No connection — will retry later" },
  delete_all: { bn: "সব মুছুন", en: "Delete all" },
  delete_confirm: { bn: "এই ফোনের সব রেকর্ড মুছে যাবে। নিশ্চিত?", en: "This deletes every case on this phone. Sure?" },
  // SAAO
  saao_title: { bn: "কৃষি অফিসারের ড্যাশবোর্ড", en: "SAAO dashboard" },
  saao_sub: { bn: "কৃষকেরা যে কেস পাঠিয়েছেন", en: "Cases farmers chose to share" },
  saao_backend_down: { bn: "সার্ভারে পৌঁছানো যায়নি — ডেমোর জন্য সাজানো কেস দেখানো হচ্ছে", en: "Server not reachable — showing seeded demo cases" },
  seeded: { bn: "সাজানো (ডেমো)", en: "seeded (demo)" },
  sms_title: { bn: "কিপ্যাড ফোনে এসএমএস", en: "SMS to a keypad phone" },
  sms_simulated: { bn: "কাল্পনিক — কোনো এসএমএস পাঠানো হয়নি", en: "Simulated — no SMS is sent" },
  received: { bn: "পেয়েছেন", en: "Received" },
  filter_all: { bn: "সব", en: "All" },
  filter_unsure: { bn: "নিশ্চিত নয়", en: "Not sure" },
  refresh: { bn: "রিফ্রেশ", en: "Refresh" },
  // Offline self-check
  selfcheck_title: { bn: "অফলাইন পরীক্ষা", en: "Offline self-check" },
  selfcheck_ok: { bn: "সব ফাইল ফোনে আছে। ইন্টারনেট ছাড়াই চলবে।", en: "Every file is on the phone. Works without internet." },
  selfcheck_dev: { bn: "ডেভেলপমেন্ট মোডে অফলাইন বন্ধ থাকে", en: "Offline caching is off in development mode" },
  // QA additions (SAAO dashboard: reply, wrong code, empty)
  saao_reply_ph: { bn: "ছোট উত্তর লিখুন (সর্বোচ্চ ৫০০ অক্ষর)", en: "Write a short reply (max 500 characters)" },
  saao_reply_send: { bn: "উত্তর পাঠান", en: "Send reply" },
  saao_reply_failed: { bn: "পাঠানো যায়নি — আবার চেষ্টা করুন", en: "Could not send — try again" },
  saao_replied: { bn: "কৃষি অফিসারের উত্তর", en: "SAAO replied" },
  saao_wrong_code: { bn: "কোডটি ঠিক নয়। রিফ্রেশ করে আবার দিন।", en: "That SAAO code was not accepted. Tap Refresh to enter it again." },
  saao_empty: { bn: "এখনো কোনো কেস আসেনি", en: "No cases received yet" },
} as const;

export type StringKey = keyof typeof S;
